# Header line; bump by hand on every text change (see gen.py)
STAND = 'Stand 2026-09-28 · v7'
# (tool, action) -> German "Was passiert" text, one plain sentence (or two)
DE = {
('bexio_contacts','create'):'Legt einen neuen Kontakt an (Kunde, Lieferant oder Person).',
('bexio_contacts','update'):'Ändert Angaben eines Kontakts, z.B. Adresse, E-Mail oder IBAN.',
('bexio_contacts','delete'):'Löscht einen Kontakt. Nur kurz danach wiederherstellbar.',
('bexio_contacts','bulk_create'):'Legt mehrere Kontakte auf einmal an.',
('bexio_contacts','restore'):'Holt einen eben gelöschten Kontakt zurück.',
('bexio_contact_relations','create'):'Verknüpft zwei Kontakte, z.B. Person mit Firma.',
('bexio_contact_relations','update'):'Ändert eine Verknüpfung zwischen zwei Kontakten.',
('bexio_contact_relations','delete'):'Löscht die Verknüpfung zwischen zwei Kontakten. Die Kontakte bleiben.',
('bexio_contact_groups','create'):'Legt eine neue Kontaktgruppe an.',
('bexio_contact_groups','update'):'Benennt eine Kontaktgruppe um.',
('bexio_contact_groups','delete'):'Löscht eine Kontaktgruppe. Die Kontakte bleiben.',
('bexio_additional_addresses','create'):'Fügt einem Kontakt eine weitere Adresse hinzu.',
('bexio_additional_addresses','update'):'Ändert eine Zusatzadresse eines Kontakts.',
('bexio_additional_addresses','delete'):'Löscht eine Zusatzadresse eines Kontakts.',
('bexio_quotes','create'):'Legt eine neue Offerte als Entwurf an.',
('bexio_quotes','update'):'Ändert eine Offerte.',
('bexio_quotes','delete'):'Löscht eine Offerte endgültig.',
('bexio_quotes','issue'):'Setzt eine Offerte von Entwurf auf "offen".',
('bexio_quotes','revert_issue'):'Setzt eine offene Offerte zurück auf Entwurf.',
('bexio_quotes','accept'):'Markiert eine Offerte als vom Kunden angenommen.',
('bexio_quotes','decline'):'Markiert eine Offerte als vom Kunden abgelehnt.',
('bexio_quotes','reissue'):'Öffnet eine angenommene oder abgelehnte Offerte wieder.',
('bexio_quotes','mark_as_sent'):'Markiert eine Offerte als verschickt. Es geht keine E-Mail raus.',
('bexio_quotes','send'):'Bexio schickt die Offerte per E-Mail an den Kunden. Nicht rückholbar.',
('bexio_quotes','copy'):'Kopiert eine Offerte in einen neuen Entwurf.',
('bexio_quotes','create_invoice'):'Erstellt aus einer Offerte eine Rechnung als Entwurf.',
('bexio_quotes','create_order'):'Erstellt aus einer Offerte einen Auftrag.',
('bexio_orders','create'):'Legt einen neuen Auftrag an.',
('bexio_orders','update'):'Ändert einen Auftrag.',
('bexio_orders','delete'):'Löscht einen Auftrag endgültig.',
('bexio_orders','edit_repetition'):'Richtet die automatische Wiederholung eines Auftrags ein oder ändert sie.',
('bexio_orders','delete_repetition'):'Stoppt die automatische Wiederholung eines Auftrags.',
('bexio_orders','create_delivery'):'Erstellt aus einem Auftrag einen Lieferschein.',
('bexio_orders','create_invoice'):'Erstellt aus einem Auftrag eine Rechnung als Entwurf.',
('bexio_deliveries','issue'):'Setzt einen Lieferschein von Entwurf auf "ausgeliefert".',
('bexio_invoices','create'):'Legt eine neue Rechnung als Entwurf an.',
('bexio_invoices','update'):'Ändert eine Rechnung (nur als Entwurf voll möglich).',
('bexio_invoices','delete'):'Löscht eine Rechnung endgültig. Nur Entwürfe.',
('bexio_invoices','issue'):'Stellt die Rechnung aus: sie wird verbucht und ist offen.',
('bexio_invoices','revert_issue'):'Nimmt die Ausstellung zurück: Rechnung wieder Entwurf, Buchung wird entfernt.',
('bexio_invoices','cancel'):'Storniert eine ausgestellte Rechnung. Sie bleibt als storniert sichtbar.',
('bexio_invoices','mark_as_sent'):'Markiert eine Rechnung als verschickt. Es geht keine E-Mail raus.',
('bexio_invoices','send'):'Bexio schickt die Rechnung per E-Mail an den Kunden. Nicht rückholbar.',
('bexio_invoices','copy'):'Kopiert eine Rechnung in einen neuen Entwurf.',
('bexio_invoice_payments','create'):'Erfasst einen Zahlungseingang auf einer Rechnung und verbucht ihn.',
('bexio_invoice_payments','delete'):'Löscht einen erfassten Zahlungseingang samt Buchung.',
('bexio_invoice_reminders','create'):'Erstellt eine Mahnung zu einer offenen Rechnung.',
('bexio_invoice_reminders','delete'):'Löscht eine Mahnung.',
('bexio_invoice_reminders','send'):'Bexio schickt die Mahnung per E-Mail an den Kunden. Nicht rückholbar.',
('bexio_invoice_reminders','mark_as_sent'):'Markiert eine Mahnung als verschickt. Es geht keine E-Mail raus.',
('bexio_invoice_reminders','mark_as_unsent'):'Markiert eine Mahnung wieder als nicht verschickt.',
('bexio_document_positions','create'):'Fügt einer Offerte, einem Auftrag oder einer Rechnung eine Position hinzu.',
('bexio_document_positions','update'):'Ändert eine Position, z.B. Menge oder Preis.',
('bexio_document_positions','delete'):'Entfernt eine Position aus einem Dokument.',
('bexio_document_comments','create'):'Schreibt einen Kommentar an ein Dokument.',
('bexio_bills','create'):'Erfasst eine neue Lieferantenrechnung als Entwurf.',
('bexio_bills','update'):'Ändert eine Lieferantenrechnung (voll nur als Entwurf).',
('bexio_bills','delete'):'Löscht eine Lieferantenrechnung.',
('bexio_bills','execute_action'):'Kopiert eine Lieferantenrechnung in einen neuen Entwurf.',
('bexio_bills','update_status'):'Bucht eine Lieferantenrechnung (Entwurf → gebucht) oder nimmt das zurück.',
('bexio_expenses','create'):'Erfasst eine neue Spese als Entwurf.',
('bexio_expenses','update'):'Ändert eine Spese (voll nur als Entwurf).',
('bexio_expenses','delete'):'Löscht eine Spese.',
('bexio_expenses','execute_action'):'Kopiert eine Spese in einen neuen Entwurf.',
('bexio_expenses','update_status'):'Bucht eine Spese (Entwurf → erledigt) oder nimmt das zurück.',
('bexio_purchase_orders','create'):'Legt eine neue Bestellung an einen Lieferanten an.',
('bexio_purchase_orders','update'):'Ändert eine Bestellung.',
('bexio_purchase_orders','delete'):'Löscht eine Bestellung.',
('bexio_outgoing_payments','create'):'Erstellt eine Zahlung an den Lieferanten zu einer Lieferantenrechnung. Geld fliesst erst nach Freigabe im E-Banking.',
('bexio_outgoing_payments','update'):'Ändert eine Lieferantenzahlung, z.B. Betrag oder Datum.',
('bexio_outgoing_payments','delete'):'Löscht eine Lieferantenzahlung.',
('bexio_accounting','create'):'Legt ein neues Kalenderjahr in der Buchhaltung an (auch alle Jahre dazwischen).',
('bexio_accounting','delete'):'Löscht einen Steuersatz endgültig.',
('bexio_currencies','create'):'Fügt eine Fremdwährung hinzu.',
('bexio_currencies','update'):'Ändert eine Fremdwährung.',
('bexio_currencies','delete'):'Löscht eine Fremdwährung.',
('bexio_manual_entries','create'):'Bucht eine manuelle Buchung ins Journal.',
('bexio_manual_entries','update'):'Ändert eine bestehende manuelle Buchung.',
('bexio_manual_entries','delete'):'Löscht eine manuelle Buchung aus dem Journal.',
('bexio_manual_entries','add_file'):'Hängt einen Beleg an eine manuelle Buchung.',
('bexio_manual_entries','delete_file'):'Entfernt einen Beleg von einer manuellen Buchung.',
('bexio_banking_payments','create'):'Erstellt einen Zahlungsauftrag. Geld fliesst erst, wenn er in Bexio ans E-Banking übermittelt ist.',
('bexio_banking_payments','update'):'Ändert einen offenen Zahlungsauftrag, z.B. Betrag, IBAN oder Datum.',
('bexio_banking_payments','cancel'):'Storniert einen Zahlungsauftrag.',
('bexio_banking_payments','delete'):'Löscht einen Zahlungsauftrag.',
('bexio_items','create'):'Legt einen neuen Artikel oder eine Dienstleistung an.',
('bexio_items','update'):'Ändert einen Artikel, z.B. Preis oder Konto.',
('bexio_items','delete'):'Löscht einen Artikel.',
('bexio_projects','create'):'Legt ein neues Projekt an.',
('bexio_projects','update'):'Ändert ein Projekt.',
('bexio_projects','delete'):'Löscht ein Projekt.',
('bexio_projects','archive'):'Archiviert ein Projekt.',
('bexio_projects','unarchive'):'Holt ein Projekt aus dem Archiv zurück.',
('bexio_project_planning','create'):'Legt einen Meilenstein oder ein Arbeitspaket an.',
('bexio_project_planning','update'):'Ändert einen Meilenstein oder ein Arbeitspaket.',
('bexio_project_planning','delete'):'Löscht einen Meilenstein oder ein Arbeitspaket.',
('bexio_timesheets','create'):'Erfasst einen Zeiteintrag.',
('bexio_timesheets','update'):'Ändert einen Zeiteintrag.',
('bexio_timesheets','delete'):'Löscht einen Zeiteintrag.',
('bexio_files','upload'):'Lädt eine Datei in die Bexio-Inbox hoch, z.B. einen Beleg.',
('bexio_files','update'):'Benennt eine Datei um oder archiviert sie.',
('bexio_files','delete'):'Löscht eine Datei aus Bexio.',
('bexio_master_data','create'):'Legt einen Stammdaten-Eintrag an, z.B. eine Einheit oder Anrede.',
('bexio_master_data','update'):'Ändert einen Stammdaten-Eintrag.',
('bexio_master_data','delete'):'Löscht einen Stammdaten-Eintrag.',
('bexio_notes','create'):'Legt eine Notiz an.',
('bexio_notes','update'):'Ändert eine Notiz.',
('bexio_notes','delete'):'Löscht eine Notiz.',
('bexio_tasks','create'):'Legt eine Aufgabe an.',
('bexio_tasks','update'):'Ändert eine Aufgabe, z.B. Status oder Termin.',
('bexio_tasks','delete'):'Löscht eine Aufgabe.',
('bexio_users','create_fictional'):'Legt einen fiktiven Benutzer an (ohne Login, z.B. für Zeiterfassung).',
('bexio_users','update_fictional'):'Ändert einen fiktiven Benutzer.',
('bexio_users','delete_fictional'):'Löscht einen fiktiven Benutzer.',
('bexio_bills','create / update + payment'):'Lieferantenrechnung mit Zahlung: löst eine Zahlung aus. Darum wie ein Zahlungsauftrag behandelt.',
}
CLS_DE = {'send':'Versand','payment':'Zahlung','final delete':'endgültig löschen','tax rate':'Steuersatz löschen','write':'direkt'}
